/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraggableWishlistIndexRouteImport } from './routes/draggable-wishlist/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraggableWishlistIndexRoute = DraggableWishlistIndexRouteImport.update({
  id: '/draggable-wishlist/',
  path: '/draggable-wishlist/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draggable-wishlist': typeof DraggableWishlistIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draggable-wishlist': typeof DraggableWishlistIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draggable-wishlist/': typeof DraggableWishlistIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draggable-wishlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draggable-wishlist'
  id: '__root__' | '/' | '/draggable-wishlist/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraggableWishlistIndexRoute: typeof DraggableWishlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draggable-wishlist/': {
      id: '/draggable-wishlist/'
      path: '/draggable-wishlist'
      fullPath: '/draggable-wishlist'
      preLoaderRoute: typeof DraggableWishlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraggableWishlistIndexRoute: DraggableWishlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
